-- Kör mot PostgreSQL om tabellen users redan finns utan geofencing-kolumner.
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_latitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_longitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS home_radius_km DOUBLE PRECISION DEFAULT 5.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_latitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_longitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notifications_paused BOOLEAN NOT NULL DEFAULT FALSE;
